### ISSUE TITLE
cos-proxy fails hook "downstream-prometheus-scrape-relation-joined" due to attribute error

### ISSUE THREAD

**Issue by Basdbruijne** [canonical/cos-proxy-operator#106] opened 2023-11-29 16:20 UTC
### Bug Description

In test run https://solutions.qa.canonical.com/testruns/9e28d172-edf3-4c8c-9412-43473f369a4f, the deployment fails because cos-proxy is in error state:

```
cos-proxy/0*                                error        idle       2/lxd/4   10.246.165.58                   hook failed: "downstream-prometheus-scrape-relation-joined"
  filebeat/9                                active       idle                 10.246.165.58                   Filebeat ready.
  nrpe/15                                   active       idle                 10.246.165.58   5666/tcp icmp   Ready
  prometheus-grok-exporter/9                active       idle                 10.246.165.58   9144/tcp        Unit is ready
  telegraf/9                                active       idle                 10.246.165.58   9103/tcp        Monitoring cos-proxy/0 (source version/commit 23.10)
  ubuntu-advantage/9                        active       idle                 10.246.165.58                   Attached (esm-apps,esm-infra)
```

### To Reproduce

1. Deploy Cos
2. Deploy the [openstack bundle](https://oil-jenkins.canonical.com/artifacts/9e28d172-edf3-4c8c-9412-43473f369a4f/generated/generated/openstack/bundle.yaml)

### Environment

Cos-proxy charm is latest/candidate rev  51

Cos itself has the following versions
```
App         Version  Status  Scale  Charm            Channel     Rev  Address  Exposed  Message
controller           active      1  juju-controller  3.1/stable   14           no       

Unit           Workload  Agent  Address     Ports      Message
controller/0*  active    idle   10.1.51.68  37017/TCP  
Model  Controller            Cloud/Region              Version  SLA          Timestamp
cos    foundations-microk8s  microk8s_cloud/localhost  3.1.6    unsupported  03:26:05Z

App           Version  Status  Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.25.0   active      1  alertmanager-k8s  stable    86  10.152.183.161  no       
catalogue              active      1  catalogue-k8s     stable    24  10.152.183.217  no       
grafana       9.2.1    active      1  grafana-k8s       stable    92  10.152.183.120  no       
loki          2.7.4    active      1  loki-k8s          stable    97  10.152.183.93   no       
prometheus    2.46.0   active      1  prometheus-k8s    stable   146  10.152.183.212  no       
traefik       2.10.4   active      1  traefik-k8s       stable   148  10.246.167.206  no       

Unit             Workload  Agent  Address      Ports  Message
alertmanager/0*  active    idle   10.1.51.70          
catalogue/0*     active    idle   10.1.51.69          
grafana/0*       active    idle   10.1.83.205         
loki/0*          active    idle   10.1.83.206         
prometheus/0*    active    idle   10.1.67.197         
traefik/0*       active    idle   10.1.51.71          

Offer         Application   Charm             Rev  Connected  Endpoint              Interface                Role
alertmanager  alertmanager  alertmanager-k8s  86   0/0        karma-dashboard       karma_dashboard          provider
grafana       grafana       grafana-k8s       92   1/1        grafana-dashboard     grafana_dashboard        requirer
loki          loki          loki-k8s          97   1/1        logging               loki_push_api            provider
prometheus    prometheus    prometheus-k8s    146  2/2        metrics-endpoint      prometheus_scrape        requirer
                                                              receive-remote-write  prometheus_remote_write  provider
```

### Relevant log output

In the debug log we see the following message repeated:

```
2023-11-29 04:51:08 DEBUG juju.worker.uniter.runner runner.go:719 starting jujuc server  {unix @/var/lib/juju/agents/unit-cos-proxy-0/agent.socket <nil>}
2023-11-29 04:51:08 DEBUG unit.cos-proxy/0.juju-log server.go:325 downstream-prometheus-scrape:162: ops 2.8.0+8.g26c6e95 up and running.
2023-11-29 04:51:08 DEBUG unit.cos-proxy/0.juju-log server.go:325 downstream-prometheus-scrape:162: Emitting Juju event downstream_prometheus_scrape_relation_joined.
2023-11-29 04:51:08 ERROR unit.cos-proxy/0.juju-log server.go:325 downstream-prometheus-scrape:162: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/./src/charm.py", line 517, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 340, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 842, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/./src/charm.py", line 442, in _downstream_prometheus_scrape_relation_joined
    self._on_nrpe_targets_changed(None)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/./src/charm.py", line 475, in _on_nrpe_targets_changed
    for alert in event.current_alerts:
AttributeError: 'NoneType' object has no attribute 'current_alerts'
2023-11-29 04:51:08 ERROR juju.worker.uniter.operation runhook.go:180 hook "downstream-prometheus-scrape-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
```

### Additional context

More logs, including crashdumps, can be found under: https://oil-jenkins.canonical.com/artifacts/9e28d172-edf3-4c8c-9412-43473f369a4f/index.html

**Comment by sed-i** [comment] 2023-12-05 23:07
Seems a duplicate of #102 (fixed by #103).
Closing for now.
Feel free to reopen if this is still an issue.

**Closed by sed-i** 2023-12-05 23:07 UTC
Labels: Type: Bug, Status: Triage

**Comment by jeffreychang911** [comment] 2024-01-04 17:44
SolQA still see this after mid Dec, with cos-proxy rev 51 from stable channel.
From this [test run](https://solutions.qa.canonical.com/testruns/40a65111-7537-409c-978e-956a68f25fad), debug log is identical to what Bas mentioned earlier.
More logs and crashdumps could be found under : https://oil-jenkins.canonical.com/artifacts/40a65111-7537-409c-978e-956a68f25fad/index.html

Please take a look as I could not reopen this issue here.

**Comment by sed-i** [comment] 2024-01-04 21:37
Hey @jeffreychang911,
I suspect rev 51 does not include the fix. Are you able to try edge?
