### ISSUE TITLE
Hook dashboards-relation-changed fails 

### ISSUE THREAD

**Issue by peppepetra** [canonical/cos-proxy-operator#104] opened 2023-11-28 17:24 UTC
### Bug Description

When relating cos-proxy with prometheus-libvirt-exporter on the dashboards relation, the hook fails with `AttributeError: 'str' object has no attribute 'get' `

### To Reproduce

1. juju deploy cos-proxy --channel edge --series focal --to lxd:15 
2. juju add-relation cos-proxy:dashboards prometheus-libvirt-exporter:dashboards

### Environment

cos-proxy rev. 52 from edge channel series focal
prometheus-libvirt-exporter rev 1 channel stable 

### Relevant log output

```shell
unit-cos-proxy-3: 17:22:58 ERROR unit.cos-proxy/3.juju-log dashboards:386: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 519, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-3/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-3/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-3/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-3/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-3/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-3/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1651, in update_dashboards
    self._upset_dashboards_on_event(event)
  File "/var/lib/juju/agents/unit-cos-proxy-3/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1655, in _upset_dashboards_on_event
    dashboards = self._handle_reactive_dashboards(event)
  File "/var/lib/juju/agents/unit-cos-proxy-3/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1797, in _handle_reactive_dashboards
    dash = t.get("dashboard", {}) or t
AttributeError: 'str' object has no attribute 'get'
unit-cos-proxy-3: 17:22:58 ERROR juju.worker.uniter.operation hook "dashboards-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by IbraAoad** [comment] 2024-02-19 13:22
Attempted to reproduce the reported issue with `cos-proxy` Edge revision 64 and `prometheus-libvirt-exporter` revision 1 on the stable channel, but was unable to reproduce.

**Steps taken to reproduce:**
1. Deployed `cos-lite` on a k8s model.
2. Offered both cos.prometheus:metrics-endpoint and cos.grafana:grafana-dashboard as CMRs.
3. Deployed `prometheus-libvirt-exporter`, `nova-compute` and `cos-proxy` edge rev 64 on a LXD model
4. Established the following relations:

```
Integration provider                    Requirer                               Interface          Type         Message
cos-proxy:downstream-grafana-dashboard  grafana:grafana-dashboard              grafana_dashboard  regular      
cos-proxy:downstream-prometheus-scrape  prometheus:metrics-endpoint            prometheus_scrape  regular      
nova-compute:compute-peer               nova-compute:compute-peer              nova               peer         
nova-compute:juju-info                  prometheus-libvirt-exporter:juju-info  juju-info          subordinate  
prometheus-libvirt-exporter:dashboards  cos-proxy:dashboards                   grafana-dashboard  regular      
prometheus-libvirt-exporter:scrape      cos-proxy:prometheus-target            http               regular
```

Relation data is constructed correctly and dashboard data is showing correctly on the cos-lite grafana instance.

I'll close the issue for now, please give it another go on `cos-proxy` edge revision 64. If the issue persists, feel free to reopen it to debug further.

**Closed by IbraAoad** 2024-02-19 13:22 UTC
Labels: Type: Bug, Status: Triage
